const hotels = [
	{
		id: 22,
		name: "코리가 호스팅하는 개인실",
		img: "a",
		price: 132000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: false, hairDryer: true },
		location: "",
	},
	{
		id: 5153,
		name: "Adam님이 호스팅하는 전원주택 전체",
		img: "b",
		price: 132000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: false, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 423,
		name: "코리가 호스팅하는 개인실",
		img: "c",
		price: 132000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 785,
		name: "Blanca님이 호스팅하는 집의 개인실",
		img: "d",
		price: 201000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 698,
		name: "Adam님이 호스팅하는 전원주택 전체",
		img: "e",
		price: 103000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 577,
		name: "Blanca님이 호스팅하는 집의 개인실",
		img: "f",
		price: 232000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 867,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "g",
		price: 54200,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 6589,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "c",
		price: 750000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1760,
		name: "Blanca님이 호스팅하는 집의 개인실",
		img: "a",
		price: 750000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1861,
		name: "Adam님이 호스팅하는 전원주택 전체",
		img: "d",
		price: 750000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 612,
		name: "Blanca님이 호스팅하는 집의 개인실",
		img: "f",
		price: 400000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 133,
		name: "Adam님이 호스팅하는 전원주택 전체",
		img: "g",
		price: 50300,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 114,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "b",
		price: 82400,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 135,
		name: "Blanca님이 호스팅하는 집의 개인실",
		img: "a",
		price: 82400,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 16,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "d",
		price: 82400,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 17,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "e",
		price: 283000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 18,
		name: "Blanca님이 호스팅하는 집의 개인실",
		img: "b",
		price: 120000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 19,
		name: "Duane & Angela님이 호스팅하는 집의 개인실",
		img: "a",
		price: 42000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 20,
		name: "Duane & Angela님이 호스팅하는 집의 개인실",
		img: "d",
		price: 42000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 21,
		name: "Duane & Angela님이 호스팅하는 집의 개인실",
		img: "e",
		price: 42000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 22,
		name: "Duane & Angela님이 호스팅하는 집의 개인실",
		img: "c",
		price: 42000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 23,
		name: "Duane & Angela님이 호스팅하는 집의 개인실",
		img: "f",
		price: 178000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2354,
		name: "Duane & Angela님이 호스팅하는 집의 개인실",
		img: "a",
		price: 178000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2532,
		name: "Duane & Angela님이 호스팅하는 집의 개인실",
		img: "e",
		price: 178000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2632,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "a",
		price: 98000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1215,
		name: "Michael님이 호스팅하는 공동 주택 전체",
		img: "e",
		price: 630000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1425,
		name: "Michael님이 호스팅하는 공동 주택 전체",
		img: "a",
		price: 630000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1225,
		name: "Michael님이 호스팅하는 공동 주택 전체",
		img: "b",
		price: 630000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1235,
		name: "Michael님이 호스팅하는 공동 주택 전체",
		img: "c",
		price: 570000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1445,
		name: "Michael님이 호스팅하는 공동 주택 전체",
		img: "a",
		price: 570000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1425,
		name: "Michael님이 호스팅하는 공동 주택 전체",
		img: "d",
		price: 570000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 115,
		name: "Michael님이 호스팅하는 공동 주택 전체",
		img: "a",
		price: 570000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 155,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "e",
		price: 600000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 156,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "f",
		price: 630000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 815,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "e",
		price: 330000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 615,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "c",
		price: 230000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 515,
		name: "Blanca님이 호스팅하는 집의 개인실",
		img: "d",
		price: 230000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 175,
		name: "Blanca님이 호스팅하는 집의 개인실",
		img: "b",
		price: 330000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 195,
		name: "Blanca님이 호스팅하는 집의 개인실",
		img: "e",
		price: 230000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 915,
		name: "Michael님이 호스팅하는 공동 주택 전체",
		img: "f",
		price: 230000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 715,
		name: "Michael님이 호스팅하는 공동 주택 전체",
		img: "d",
		price: 230000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 176,
		name: "Tina님이 호스팅하는 집의 개인실",
		img: "c",
		price: 150000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 186,
		name: "Tina님이 호스팅하는 집의 개인실",
		img: "a",
		price: 150000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1456,
		name: "Samantha님이 호스팅하는 통나무집 전체",
		img: "b",
		price: 150000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1347,
		name: "Samantha님이 호스팅하는 통나무집 전체",
		img: "a",
		price: 420000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1347,
		name: "Samantha님이 호스팅하는 통나무집 전체",
		img: "e",
		price: 420000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1647,
		name: "Tina님이 호스팅하는 집의 개인실",
		img: "c",
		price: 420000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1348,
		name: "Samantha님이 호스팅하는 통나무집 전체",
		img: "b",
		price: 530000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1538,
		name: "Tina님이 호스팅하는 집의 개인실",
		img: "e",
		price: 530000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 1128,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "d",
		price: 530000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 12239,
		name: "Beth님이 호스팅하는 초소형 주택",
		img: "a",
		price: 234000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2420,
		name: "Tina님이 호스팅하는 집의 개인실",
		img: "f",
		price: 523000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2530,
		name: "Samantha님이 호스팅하는 통나무집 전체",
		img: "c",
		price: 523000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2630,
		name: "Samantha님이 호스팅하는 통나무집 전체",
		img: "a",
		price: 723000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2350,
		name: "Adam님이 호스팅하는 전원주택 전체",
		img: "b",
		price: 773000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2530,
		name: "Adam님이 호스팅하는 전원주택 전체",
		img: "a",
		price: 923000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2230,
		name: "Adam님이 호스팅하는 전원주택 전체",
		img: "g",
		price: 823000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2530,
		name: "Adam님이 호스팅하는 전원주택 전체",
		img: "g",
		price: 923000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
	{
		id: 2670,
		name: "Samantha님이 호스팅하는 통나무집 전체",
		img: "g",
		price: 723000,
		unavailableDate: [],
		rooms: { peopleMax: 4, bedroom: 1, bed: 1, bathroom: 1 },
		options: { kitchen: true, wifi: true, airConditioner: true, hairDryer: true },
		location: "",
	},
];

export default hotels;
